// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DEVICES_FBS_H_
#define FLATBUFFERS_GENERATED_DEVICES_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace fbs {

struct DeviceType;
struct DeviceTypeBuilder;

struct Device;
struct DeviceBuilder;

struct DeviceTypeList;
struct DeviceTypeListBuilder;

struct DeviceList;
struct DeviceListBuilder;

struct DeviceType FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceTypeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_DESCRIPTION = 8,
    VT_CREATED_AT = 10,
    VT_LAST_UPDATE = 12,
    VT_ACTIVE = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::String *created_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_AT);
  }
  const ::flatbuffers::String *last_update() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LAST_UPDATE);
  }
  bool active() const {
    return GetField<uint8_t>(VT_ACTIVE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_CREATED_AT) &&
           verifier.VerifyString(created_at()) &&
           VerifyOffset(verifier, VT_LAST_UPDATE) &&
           verifier.VerifyString(last_update()) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVE, 1) &&
           verifier.EndTable();
  }
};

struct DeviceTypeBuilder {
  typedef DeviceType Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DeviceType::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(DeviceType::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(DeviceType::VT_DESCRIPTION, description);
  }
  void add_created_at(::flatbuffers::Offset<::flatbuffers::String> created_at) {
    fbb_.AddOffset(DeviceType::VT_CREATED_AT, created_at);
  }
  void add_last_update(::flatbuffers::Offset<::flatbuffers::String> last_update) {
    fbb_.AddOffset(DeviceType::VT_LAST_UPDATE, last_update);
  }
  void add_active(bool active) {
    fbb_.AddElement<uint8_t>(DeviceType::VT_ACTIVE, static_cast<uint8_t>(active), 0);
  }
  explicit DeviceTypeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceType> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceType>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceType> CreateDeviceType(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_at = 0,
    ::flatbuffers::Offset<::flatbuffers::String> last_update = 0,
    bool active = false) {
  DeviceTypeBuilder builder_(_fbb);
  builder_.add_last_update(last_update);
  builder_.add_created_at(created_at);
  builder_.add_description(description);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_active(active);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeviceType> CreateDeviceTypeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const char *description = nullptr,
    const char *created_at = nullptr,
    const char *last_update = nullptr,
    bool active = false) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto created_at__ = created_at ? _fbb.CreateString(created_at) : 0;
  auto last_update__ = last_update ? _fbb.CreateString(last_update) : 0;
  return fbs::CreateDeviceType(
      _fbb,
      id__,
      name__,
      description__,
      created_at__,
      last_update__,
      active);
}

struct Device FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE_ID = 6,
    VT_DEVICE_NAME = 8,
    VT_MANUFACTURER = 10,
    VT_INTERFACE = 12,
    VT_DESCRIPTION = 14,
    VT_CREATED_AT = 16,
    VT_LAST_UPDATE = 18,
    VT_ACTIVE = 20
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *type_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE_ID);
  }
  const ::flatbuffers::String *device_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_NAME);
  }
  const ::flatbuffers::String *manufacturer() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MANUFACTURER);
  }
  const ::flatbuffers::String *interface() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INTERFACE);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::String *created_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_AT);
  }
  const ::flatbuffers::String *last_update() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LAST_UPDATE);
  }
  bool active() const {
    return GetField<uint8_t>(VT_ACTIVE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_TYPE_ID) &&
           verifier.VerifyString(type_id()) &&
           VerifyOffset(verifier, VT_DEVICE_NAME) &&
           verifier.VerifyString(device_name()) &&
           VerifyOffset(verifier, VT_MANUFACTURER) &&
           verifier.VerifyString(manufacturer()) &&
           VerifyOffset(verifier, VT_INTERFACE) &&
           verifier.VerifyString(interface()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_CREATED_AT) &&
           verifier.VerifyString(created_at()) &&
           VerifyOffset(verifier, VT_LAST_UPDATE) &&
           verifier.VerifyString(last_update()) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVE, 1) &&
           verifier.EndTable();
  }
};

struct DeviceBuilder {
  typedef Device Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Device::VT_ID, id);
  }
  void add_type_id(::flatbuffers::Offset<::flatbuffers::String> type_id) {
    fbb_.AddOffset(Device::VT_TYPE_ID, type_id);
  }
  void add_device_name(::flatbuffers::Offset<::flatbuffers::String> device_name) {
    fbb_.AddOffset(Device::VT_DEVICE_NAME, device_name);
  }
  void add_manufacturer(::flatbuffers::Offset<::flatbuffers::String> manufacturer) {
    fbb_.AddOffset(Device::VT_MANUFACTURER, manufacturer);
  }
  void add_interface(::flatbuffers::Offset<::flatbuffers::String> interface) {
    fbb_.AddOffset(Device::VT_INTERFACE, interface);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(Device::VT_DESCRIPTION, description);
  }
  void add_created_at(::flatbuffers::Offset<::flatbuffers::String> created_at) {
    fbb_.AddOffset(Device::VT_CREATED_AT, created_at);
  }
  void add_last_update(::flatbuffers::Offset<::flatbuffers::String> last_update) {
    fbb_.AddOffset(Device::VT_LAST_UPDATE, last_update);
  }
  void add_active(bool active) {
    fbb_.AddElement<uint8_t>(Device::VT_ACTIVE, static_cast<uint8_t>(active), 0);
  }
  explicit DeviceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Device> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Device>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Device> CreateDevice(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> device_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> manufacturer = 0,
    ::flatbuffers::Offset<::flatbuffers::String> interface = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_at = 0,
    ::flatbuffers::Offset<::flatbuffers::String> last_update = 0,
    bool active = false) {
  DeviceBuilder builder_(_fbb);
  builder_.add_last_update(last_update);
  builder_.add_created_at(created_at);
  builder_.add_description(description);
  builder_.add_interface(interface);
  builder_.add_manufacturer(manufacturer);
  builder_.add_device_name(device_name);
  builder_.add_type_id(type_id);
  builder_.add_id(id);
  builder_.add_active(active);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Device> CreateDeviceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *type_id = nullptr,
    const char *device_name = nullptr,
    const char *manufacturer = nullptr,
    const char *interface = nullptr,
    const char *description = nullptr,
    const char *created_at = nullptr,
    const char *last_update = nullptr,
    bool active = false) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto type_id__ = type_id ? _fbb.CreateString(type_id) : 0;
  auto device_name__ = device_name ? _fbb.CreateString(device_name) : 0;
  auto manufacturer__ = manufacturer ? _fbb.CreateString(manufacturer) : 0;
  auto interface__ = interface ? _fbb.CreateString(interface) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto created_at__ = created_at ? _fbb.CreateString(created_at) : 0;
  auto last_update__ = last_update ? _fbb.CreateString(last_update) : 0;
  return fbs::CreateDevice(
      _fbb,
      id__,
      type_id__,
      device_name__,
      manufacturer__,
      interface__,
      description__,
      created_at__,
      last_update__,
      active);
}

struct DeviceTypeList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceTypeListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::DeviceType>> *types() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::DeviceType>> *>(VT_TYPES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPES) &&
           verifier.VerifyVector(types()) &&
           verifier.VerifyVectorOfTables(types()) &&
           verifier.EndTable();
  }
};

struct DeviceTypeListBuilder {
  typedef DeviceTypeList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_types(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::DeviceType>>> types) {
    fbb_.AddOffset(DeviceTypeList::VT_TYPES, types);
  }
  explicit DeviceTypeListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceTypeList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceTypeList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceTypeList> CreateDeviceTypeList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::DeviceType>>> types = 0) {
  DeviceTypeListBuilder builder_(_fbb);
  builder_.add_types(types);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeviceTypeList> CreateDeviceTypeListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::DeviceType>> *types = nullptr) {
  auto types__ = types ? _fbb.CreateVector<::flatbuffers::Offset<fbs::DeviceType>>(*types) : 0;
  return fbs::CreateDeviceTypeList(
      _fbb,
      types__);
}

struct DeviceList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Device>> *devices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Device>> *>(VT_DEVICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DEVICES) &&
           verifier.VerifyVector(devices()) &&
           verifier.VerifyVectorOfTables(devices()) &&
           verifier.EndTable();
  }
};

struct DeviceListBuilder {
  typedef DeviceList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_devices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Device>>> devices) {
    fbb_.AddOffset(DeviceList::VT_DEVICES, devices);
  }
  explicit DeviceListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceList> CreateDeviceList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Device>>> devices = 0) {
  DeviceListBuilder builder_(_fbb);
  builder_.add_devices(devices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeviceList> CreateDeviceListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::Device>> *devices = nullptr) {
  auto devices__ = devices ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Device>>(*devices) : 0;
  return fbs::CreateDeviceList(
      _fbb,
      devices__);
}

inline const fbs::DeviceList *GetDeviceList(const void *buf) {
  return ::flatbuffers::GetRoot<fbs::DeviceList>(buf);
}

inline const fbs::DeviceList *GetSizePrefixedDeviceList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fbs::DeviceList>(buf);
}

inline bool VerifyDeviceListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::DeviceList>(nullptr);
}

inline bool VerifySizePrefixedDeviceListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::DeviceList>(nullptr);
}

inline void FinishDeviceListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbs::DeviceList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDeviceListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbs::DeviceList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_DEVICES_FBS_H_
